### ISSUE TITLE
Error line 40

### ISSUE THREAD

**Issue by IngJuanMunoz** [gustavogino/Vehicle-Counter#1]
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    img,contorno,h = cv2.findContours(dilatada,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by gustavogino** [comment]
try: _,img,contorno,h = cv2.findContours(dilatada,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
I'm add "_" in receive variables

**Comment by gustavogino** [comment]
Try remove variable "h".

Code: img,contorno = cv2.findContours(dilatada,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
